sonar.projectKey=edwin-oghenetejiri1_retrogame-microservices-k8s
sonar.organization=edwin-oghenetejiri1
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out